name: CICD WagtailApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml
        directory: ./server_conf/
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [myservers]
          ${{secrets.HOST_IP}} ssh_ansible_user=azureuser
