name: CICD WagtailApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

    - run: terraform init
      working-directory: ./infrastructure/
    
    - run: terraform plan -no-color
      working-directory: ./infrastructure/
    
    - run: terraform apply -auto-approve 
      id: terraform_apply
      working-directory: ./infrastructure/
    
    - name: Call terraform output
      id: tf_output
      run: |
        output=$(terraform output server-ip)
        echo "::set-output name=server_ip::$(output)"

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml
        directory: ./server_conf/
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [myservers]
          ${{steps.tf_output.outputs.server_ip}} ansible_ssh_user=azureuser