---

- hosts: myservers
  become: true

  tasks:
  - name: Instalar software y dependencias
    apt:
      name:
      - python3
      - apache2
      - libjpeg-dev
      - libfreetype6-dev
      - zlib1g-dev
      - libtiff-dev
      - build-essential
      - python-setuptools
      - wget
      - libapache2-mod-wsgi-py3
      state: latest
      update_cache: yes
  - name: Activar mod de apache wsgi
    apache2_module:
      name: wsgi
      state: present
  - name: Desactivar sitio por defecto
    command: a2dissite 000-default.conf
  - name: Copiar archivo de configuracion del sitio
    copy:
      src: ./files/website.conf
      dest: /etc/apache2/sites-available/website.conf
  - name: Activar nuestro sitio de wagtail
    command: a2ensite website.conf
  - name: Copiar los archivos del sitio web
    copy:
      src: ./../application/
      dest: /home/azureuser/application
      owner: www-data
      group: www-data
  - name: Instalar dependencias de python
    pip:
      virtualenv: /home/azureuser/application/.venv
      requirements: /home/azureuser/application/requirements.txt
      state: present
  - name: Construir migraciones
    command: python3 manage.py makemigrations
  - name: Realizar migraciones
    command: python3 manage.py migrate
  - name: Obtener archivos estaticos
    command: python3 manage.py collecstatic
  - name: Reiniciar servidor
    service:
      name: apache2
      state: restarted
