---

- hosts: myservers
  become: true

  tasks:
  - name: Instalar software y dependencias
    apt:
      name:
      - python3
      - apache2
      - libjpeg-dev
      - libfreetype6-dev
      - zlib1g-dev
      - libtiff-dev
      - build-essential
      - python-setuptools
      - wget
      - libapache2-mod-wsgi-py3
      state: latest
      update_cache: yes
  - name: Activar mod de apache wsgi
    apache2_module:
      name: wsgi
      state: present
  - name: Desactivar sitio por defecto
    command: a2dissite 000-default.conf
  - name: Copiar archivo de configuracion del sitio
    copy:
      src: ./files/website.conf
      dest: /etc/apache2/sites-available/website.conf
  - name: Activar nuestro sitio de wagtail
    command: a2ensite website.conf
